development:
  adapter: postgresql
  encoding: unicode
  database: ejercicio2_development
  pool: 5
  username: saul
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: ejercicio2_test
  pool: 5
  username: saul
  password: 123456